spring.application.name=MVC-KP

spring.freemarker.expose-request-attributes=true

spring.datasource.url=jdbc:postgresql://localhost:5432/MVCDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379

dropbox.accessToken=sl.u.AGUAIonzCOO5EpTcvoswoTwzLw1QLT2HoeIkZOZ-MneEqcL_mU3jfMvpPz_qLuADdr4HX0jT7yxDGDNpe9I35v1ZvhIn5hkNMzTC-OYF4sQuF2HO-N2tL9ic09TIR1ynF2LbrKHkruC24q_XFXuXHrLF8ez7WxKVJ_OyzKQwzMDY7nQUY7onmuZSckLfVY7LCX0J7e9IId0zxBMihhfUMRpUHPTamNHQwlN2GBW9c_QzxVIgUFn3OAMZ7I4uooAVyQL-6M0E90HuE0CNLCD8hlcJQzy77P5Vh266liEcEv-4LbYvVe21ihGNZDoYz_FEmm8zyES7tXW8zRVDi0FHQbu0czJHd6pSAW8QRAuovwEDn258lASKcjeC7rSzfrqeX3OwAwqEw8dJ_d-OOq3hzVSpiJqmF-b7WrvRaWx3Hzzw8XQ6NBSDuQd3zsEjR95LdmhGLV0ZNmznBGpvSbAL-65slvpEO-IsC9fd26CqKhJPKNLCeUJGa2vFXkxlgch1z4fJSECSDoUDo18w84EAMr1IgzsNxhpdcLqQfX4tFzHzXVYrQ07IgpRdvPp3Vg3nRLr-fTRTK6fDHE1-hmJ1zsoJzyMOCSRL7U2i3JPhDSM4qBzYUSkx5V3BjLQ-rH94JPjjwJ_0qiLP8gDZePiZOJT0dUbvq5BJbSTzCfrVasyWVc5NGx3Q8V6GS-JY5plcXr7lTl2e16IpSZIXVB6diZZFiCt9zRVJSOHLtfVnbY3lR9MQxxPArHJLyqSXZLHLAU4Yyg_OdM2dL218mH0D-G46CKoZZpEKBablITsZG85qBTngqENGoksPb3g4P0A7bkL-LdYqMKc1i6uM1qQIWr5fyL6J1ZYeF2Q_7SWuqONg6FTS-EwND-33LJZqmF-kBV6OoLpXLxDPifswrkZZPX7zZgVtPEsyp5m32zoXXWgdH6JR4h9y5Fif2gq5wh7BqR3o8a31SZe0EkNmbRGRoHW8UWsLz84eLdstFavEi7PgcU8-T6U3TQm7JMJH2htmALUHGAHDn4FplPw1O523MRHhUCMB0mBMiHvCrEjrPO5eBFGM4_IDivzuq69fucacAwwLQdfpKHbz3TQo6TpDvccfVBbCyY74MKtxjbWO-y4rw0frU92HG8gkrLo4-oHLyWuxmdEOjrg2hkRwDcqsdw8tAUZTzt1CVTWDcClta7-W2L56OBcxelTOVMBUyhEmHW2GmcBoJBeAqd2c562r2ogTV9hewfId3_S-vYIGxeiXVFVYmCrfpn7CGgTy9N79vD1NaQ7m4EFoR3ENjKZojsEjWFr4VQy6pNcntt2HSi4g-4nkz7dKg5UzE63GUoodywfXkamxt7uSGbTmnvEY1Ngo9c-PQhlfgJme-m36fkYF6uwGWNB2CZrjuaOGYaHNSQ_HYzx6xFLgMgwbxp2enYy6ZJea_N0sYlVXcr29k1u_--zqOo2PENcTwdZPZkF-U39VZ83537dF_hVQx-9pFrMi

dropbox.dropboxName=PcStoreMVC
dropbox.imgPath=/images/

spring.mail.username=andreevmatvei121004
spring.mail.password=csdfedqtejpdibkj
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.debug=true