spring.application.name=MVC-KP

spring.freemarker.expose-request-attributes=true

spring.datasource.url=jdbc:postgresql://localhost:5432/MVCDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=localhost
spring.data.redis.port=6379

dropbox.accessToken=sl.u.AFvkTjAbgID2ZPcPbAnAdy0VsgIVsA0SB4jwcJutdJZciRGiURce4VKnSJGIY57E3yjLsduThI4u5m46vSiNNF1CjVo_h5nYYWpuboS5o7S2oLHVnSA85B9c4OrMv8je3M98AIGJwha-UwwikjsLddH3_k86Dii8Eg1FnSegFwAMM4gWeWX2NetO9AsHAtKlKSc2FIsCwC34ksT7iB5tOmrR9Rfdzzdd_pVUO1alYEkLSeyMu_QEMlTCp8HxpDXg9QYd03Zdxjp78XMAETNM6MW9LCh5p_10ZTqhuThJmFoHxs1Mlh2SDjwJql9gZm_bxqe2yMw3pldrwiRMOuMI781GVvwtKjX7Wgbn_jnqd8lYWthz5dbWmB63p7vpqJW_8Y2UGIOyqNPB9EKdrq8K79Mb7pIGrB57mF7TDzBuXP5-lxkc4W3xtc5hNOw6oQqWZtoWVkXI9I7tJltN5wfTaNHOnrQHJx5I8Ts7wceze5u1XBykwRY9rWdPLBWC1D5t5NZ8hWgBZkDr9q0B9cJ41hYLZfPutIK5V_b5LDX--hyoeVMiVEmakJOI4n3qHgCV-SOR89i6smbGLxwhibKBVQm60jU1HCoGkqqF1LXw4FZuYW0wFIvFDe80uA1oCwdc0dA4ne0XGx_MxSsxNekRv6m0UbdbRUwZOkCRC8w9f55Bxty66KXj0fKU6WrW-zLpczdicHTnaeXCB8RZNoP9ssGiPSDeaOw0pvtkaO9iaOwXZqe6oqaMRBqaWoufPV4ideNuvaTFP9L5ibZK87yoF08BtF2_bcgcafuSE_v02Xcs2xKfppstczlXzI_NrtQKRwvL1rglV-htedKsRTQXE4FVLdIfhe1MXw2Z2Qu2IvzjzD_RejNX9OSHTisa8r6sd_PpGbMxqhTPCx4SCJ9bRRrgJovBCuHQw3DthAh94tAUmhd5rXHbOnHZwrpHl_QYkcxmoE7xPkYZEPhEpcHsRhyBlH-6pFwak9dNG9bJEDeuUK0eeIFsGewv_wzxbyXCRIs6xP15NWIwjEPC7hTeXES_r0bAhxwYL_Dl8wLzH46XlLod2NVkNdOW4HdVrihRllgXGtx7iTtDKAuXkrl5oOARbz6-LpFaDdPISmX2R6QeiOm9Pk5_ReMZsjsoI_dUP9nHuG6j3Hj_Kc_Z1PpO3mhDOML_NYf3kBVuO4SapvvhMbI1aXgDGojO8GTQfpiO_Thy593VF4KnySbr_U4O77YKYo_rAVQLBAxYEInSFo-BqOXvT9gG5VgzAvopaYjnhYmKlVmcwjjB7MwVpRCCllbynkyrF9eNoilAW0K9KsLyak_YJzoJHTqsOwWS6dGno5oE8ueW_1fZ7jxacPcYa8GNm97Y95qoQxAkASkfslx7zTq6WTo_CHJ0zh0kuGvNE62cODDoK4bNtlatAOWHqik8RjmJ-YmgvGn0CBODFmC-Kc9Sqx7IzXURTIfCWh0mU0lKAiEoTVEfmzG05HcND6xC

dropbox.dropboxName=PcStoreMVC
dropbox.imgPath=/images/

spring.mail.username=andreevmatvei121004
spring.mail.password=csdfedqtejpdibkj
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.debug=true