spring.application.name=MVC-KP

spring.freemarker.expose-request-attributes=true

spring.datasource.url=jdbc:postgresql://localhost:5432/MVCDB
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.username=andreevmatvei121004
spring.mail.password=csdfedqtejpdibkj
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.debug=true